baseURL = "https://deepin-community.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "deepin 社区博客"
theme = "anubis"
ignoreFiles = ['README.md']

[params]
  languageCode = "zh-cn"
  author = "deepin"
  email = "blog@deepin.org"
  avatar = "/images/me.png"
  description = ""
  readMore = true
  rssAsSocialIcon = true
  style = "auto"

[[params.social]]
  id = "github"
  name = "deepin-community"

[menu]
[[menu.main]]
identifier = "index"
name = "首页"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 30

[[menu.main]]
name = "归档"
identifier = "archive"
url = "/posts/"
weight = 40

[taxonomies]
  author = "authors"
  category = "categories"
  series = "series"
  tag = "tags"
